name: Cypress Testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cypress:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Environmental Variables
        run: |
          touch .env
          echo NEXT_PUBLIC_SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> .env
          echo NEXT_PUBLIC_BUTTONDOWN_TOKEN=${{ secrets.BUTTONDOWN_TOKEN }} >> .env
          echo NEXT_PUBLIC_LC_KEY=${{ secrets.LC_KEY }} >> .env
          echo NEXT_PUBLIC_LC_ID=${{ secrets.LC_ID }} >> .env
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn --immutable
          build: yarn run build
          start: yarn run start
          browser: chrome
      - name: Cache Next.js Build
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]sx?') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
