name: Cypress Testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cypress:
    name: Testing
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.0-chrome99-ff97
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout & Setup Yarn & Install Dependencies
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Setup Environmental Variables
        run: |
          touch .env
          echo NEXT_PUBLIC_SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> .env
          echo SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} >> .env
          echo SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }} >> .env
          echo SENTRY_ORG=${{ secrets.SENTRY_ORG }} >> .env
          echo NEXT_PUBLIC_BUTTONDOWN_TOKEN=${{ secrets.BUTTONDOWN_TOKEN }} >> .env
          echo NEXT_PUBLIC_LC_KEY=${{ secrets.LC_KEY }} >> .env
          echo NEXT_PUBLIC_LC_ID=${{ secrets.LC_ID }} >> .env
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          build: yarn run build
          start: yarn run start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          record: true
          parallel: true
          browser: chrome
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Next.js Build
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]sx?') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
