app = "ouorz-wordpress"

[env]
  WORDPRESS_CONFIG_EXTRA = "define(\"MYSQL_CLIENT_FLAGS\", MYSQLI_CLIENT_SSL);define(\"WP_DEBUG_DISPLAY\", false);ini_set(\"display_errors\",\"Off\");ini_set(\"error_reporting\", E_ALL & ~E_NOTICE);"

[mounts]
  destination = "/var/www/html/wp-content"
  source = "ouorz_wordpress_wp_content"

[[services]]
  internal_port = 80
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 50
    soft_limit = 25

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = 5000
    timeout = 2000
